### ISSUE TITLE
Build-in LESS CSS nesting is not working properly

### ISSUE THREAD

**Issue by mateuszgachowski** [totaljs/framework#157]
Less nesting is not working correctly, for example:

``` css
body {
  h1 {
    span {
      background: #fff;
    }
  }
}
```

Should compile to something like this:

``` css
body h1 span {
 background: #fff;
}
```

but compiles to:

``` css
body{h1{span{background:#fff;}}}
```

So it do not compiles at all :)
